{{- if and .Values.app.config.security.ssl.enabled .Values.app.config.security.ssl.secret.generate }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.app.config.security.ssl.secret.name }}
  labels:
    app: ansible-lifecycle-driver
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "gen-cert" . ) | indent 2 }}
{{- end }}